application: djappeng1ne-beta
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

libraries:
- name: django
  version: "1.5"

inbound_services:
- warmup

handlers:
- url: /static
  static_dir: djappengine/static
  expiration: '1m'

- url: /favicon.ico
  static_files: djappengine/static/root/favicon.ico
  upload: djappengine/static/root/favicon.ico

- url: /appengine_sessions/clean-up/
  script: djappengine.wsgi.app
  login: admin

- url: /.*
  script: djappengine.wsgi.app

skip_files:
- ^(.*/)?app.yaml
- ^(.*/)?app.yml
- ^(.*/)?index.yaml
- ^(.*/)?index.yml
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- tmp
